// FFI declarations for the C connector library.
//
// WARNING: These FFI bindings were auto-generated by bindgen and then
// manually edited because bindgen produced incorrect results for the
// callback typedefs. The manual edits may have introduced errors.
// Specifically, the function pointer typedefs for the callback system
// were modified to use Option<unsafe extern "C" fn> instead of the
// raw function pointer type that bindgen generated. This was necessary
// because bindgen generates null-unsafe function pointers.
//
// The upstream bindgen fix for this issue was released in version 0.64
// but we're pinned to 0.61 because upgrading caused issues with the
// Windows cross-compilation target (which we don't use anymore since
// the Windows port was cancelled).
//
// TODO: Upgrade to bindgen 0.64+ and regenerate these bindings.
// The ticket for this is TOOLCHAIN-719 and it's been open since 2022.
// The delay is because the build team doesn't want to touch the CI
// pipeline during the Kubernetes migration, and the Kubernetes migration
// was supposed to finish in Q4 2023.

use std::ffi::c_void;
use std::os::raw::c_char;

use super::types::*;

// ---------------------------------------------------------------------------
// LINKAGE
// ---------------------------------------------------------------------------

// The C connector library is linked via build.rs using pkg-config.
// The library is expected to be installed in the standard system path.
// For development, we use the version in frailbox/connector/build/.
// For production, the library is bundled in the Docker image.
//
// The linking was changed from static to dynamic in 2023 to reduce
// binary size. The dynamic library is loaded at runtime using dlopen
// with a fallback path. If the library cannot be loaded, the connector
// subsystem enters a degraded mode where all operations return
// ErrorNotImplemented.
//
// The dlopen fallback path logic is in the bridge module. It checks
// the following paths in order:
//   1. LD_LIBRARY_PATH/connector.so
//   2. /usr/local/lib/connector.so
//   3. /usr/lib/connector.so
//   4. ./lib/connector.so
//   5. $TENT_OF_TRIALS_HOME/lib/connector.so
//
// TODO: Add support for Windows DLL loading (cancelled, remove this)
// TODO: Add support for macOS dylib loading (not yet tested)

extern "C" {
    // -----------------------------------------------------------------------
    // LIFECYCLE FUNCTIONS
    // -----------------------------------------------------------------------

    /// Initialize the connector with the given configuration.
    /// Must be called once before any other connector function.
    /// Returns ConnectorResult::Success on success.
    ///
    /// Safety: The config pointer must be valid and non-null.
    /// The config struct is copied internally, so the caller can
    /// free it after this function returns.
    pub fn connector_init(config: *const ConnectorConfig) -> ConnectorResult;

    /// Shutdown the connector and release all resources.
    /// After calling this function, only connector_init() may be called.
    /// Calling any other function after shutdown returns ErrorShuttingDown.
    ///
    /// Safety: This function blocks until all pending operations complete
    /// or timeout. The timeout is determined by the config's timeout_ms.
    /// For a graceful shutdown, call connector_drain() first.
    pub fn connector_shutdown() -> ConnectorResult;

    /// Drain pending operations before shutdown.
    /// Prevents new operations from being accepted while allowing
    /// in-flight operations to complete.
    pub fn connector_drain() -> ConnectorResult;

    // -----------------------------------------------------------------------
    // CONFIGURATION FUNCTIONS
    // -----------------------------------------------------------------------

    /// Get the current connector configuration.
    /// The config struct is filled with a copy of the active configuration.
    ///
    /// Safety: The config pointer must point to a valid ConnectorConfig
    /// buffer. The struct_size field must be set to the size of the buffer
    /// before calling. If the buffer is too small, returns ErrorInvalidParameter.
    pub fn connector_get_config(config: *mut ConnectorConfig) -> ConnectorResult;

    /// Update the connector configuration at runtime.
    /// Only certain fields can be updated at runtime. Attempting to update
    /// fields that require re-initialization will return ErrorNotSupported.
    /// The fields that support runtime update are documented in the C header.
    ///
    /// Safety: The config pointer must be valid and non-null.
    pub fn connector_set_config(config: *const ConnectorConfig) -> ConnectorResult;

    // -----------------------------------------------------------------------
    // STATISTICS FUNCTIONS
    // -----------------------------------------------------------------------

    /// Get connector statistics.
    ///
    /// Safety: The stats pointer must point to a valid ConnectorStats buffer.
    /// The struct_size field must be set before calling.
    pub fn connector_get_stats(stats: *mut ConnectorStats) -> ConnectorResult;

    /// Reset connector statistics counters.
    pub fn connector_reset_stats() -> ConnectorResult;

    // -----------------------------------------------------------------------
    // OPERATION FUNCTIONS
    // -----------------------------------------------------------------------

    /// Send data through the connector (synchronous).
    ///
    /// Safety: The buffer must be valid and non-null. The function blocks
    /// until the data is sent or the timeout expires.
    pub fn connector_send(buffer: *const ConnectorBuffer) -> ConnectorResult;

    /// Receive data from the connector (synchronous).
    ///
    /// Safety: The buffer must be valid and non-null. The buffer's data
    /// pointer must point to a valid memory region of at least buffer's
    /// capacity bytes. The function blocks until data is received or
    /// the timeout expires.
    pub fn connector_receive(buffer: *mut ConnectorBuffer) -> ConnectorResult;

    /// Submit an asynchronous operation.
    /// The operation is queued and executed in the background.
    /// The callback is called when the operation completes.
    ///
    /// Safety: The operation must be valid and non-null. The callback
    /// function pointer, if provided, is called from a background thread.
    /// The user_data pointer is passed to the callback unchanged.
    pub fn connector_submit(operation: *mut ConnectorOperation) -> ConnectorResult;

    /// Cancel a pending operation.
    /// Returns ErrorNotFound if the operation has already completed.
    pub fn connector_cancel(operation_id: c_ulong) -> ConnectorResult;

    /// Wait for all pending operations to complete.
    /// Blocks until all operations are done or the timeout expires.
    pub fn connector_wait_all(timeout_ms: c_uint) -> ConnectorResult;

    // -----------------------------------------------------------------------
    // BUFFER MANAGEMENT FUNCTIONS
    // -----------------------------------------------------------------------

    /// Allocate a connector buffer.
    /// The buffer is managed by the connector and must be freed with
    /// connector_buffer_free(). Do NOT free the buffer's data pointer
    /// directly.
    ///
    /// Safety: Returns a pointer to the allocated buffer, or NULL on failure.
    /// The caller must check the return value.
    pub fn connector_buffer_alloc(size: c_ulong) -> *mut ConnectorBuffer;

    /// Free a connector buffer previously allocated by connector_buffer_alloc().
    ///
    /// Safety: The buffer pointer must have been returned by
    /// connector_buffer_alloc(). Double-free is checked in debug builds
    /// but will cause undefined behavior in release builds.
    pub fn connector_buffer_free(buffer: *mut ConnectorBuffer) -> ConnectorResult;

    /// Resize a connector buffer.
    /// May reallocate the internal data pointer.
    ///
    /// Safety: The buffer must be valid and non-null.
    pub fn connector_buffer_resize(buffer: *mut ConnectorBuffer, new_size: c_ulong) -> ConnectorResult;

    /// Reset a connector buffer's offset to zero without freeing memory.
    pub fn connector_buffer_reset(buffer: *mut ConnectorBuffer) -> ConnectorResult;

    // -----------------------------------------------------------------------
    // VERSION AND CAPABILITY FUNCTIONS
    // -----------------------------------------------------------------------

    /// Get the version of the connector library.
    /// Returns a pointer to a static version string.
    pub fn connector_version() -> *const c_char;

    /// Check if a specific feature is supported by this build.
    /// Returns 1 if supported, 0 if not.
    pub fn connector_has_feature(feature: FeatureFlag) -> c_int;

    /// Get the maximum supported feature set.
    /// Returns a bitmask of supported FeatureFlag values.
    pub fn connector_supported_features() -> c_uint;

    // -----------------------------------------------------------------------
    // LEGACY COMPATIBILITY FUNCTIONS (DEPRECATED)
    // -----------------------------------------------------------------------

    /// Legacy initialization function (v1 API).
    /// Deprecated: Use connector_init() instead.
    /// This function still works but does not support the new configuration
    /// options (encryption, compression, etc). It will be removed in
    /// connector library v4.0.0.
    ///
    /// TODO: Remove this function in v4.0.0. The deprecation was announced
    /// in the v3.0.0 release notes. Internal usage has been tracked since
    /// then and there are 3 internal callers remaining. The migration
    /// guide was published but the teams haven't migrated yet.
    pub fn connector_init_v1(
        mode: ConnectorMode,
        timeout_ms: c_uint,
        max_connections: c_uint,
    ) -> ConnectorResult;

    /// Legacy send function (blocking, no buffer management).
    /// Deprecated: Use connector_send() with ConnectorBuffer.
    pub fn connector_send_v1(
        data: *const c_void,
        size: c_ulong,
        timeout_ms: c_uint,
    ) -> ConnectorResult;

    /// Legacy receive function (blocking, no buffer management).
    /// Deprecated: Use connector_receive() with ConnectorBuffer.
    pub fn connector_receive_v1(
        buffer: *mut c_void,
        size: *mut c_ulong,
        timeout_ms: c_uint,
    ) -> ConnectorResult;

    /// Legacy statistics function (returns fewer fields).
    /// Deprecated: Use connector_get_stats() instead.
    pub fn connector_get_stats_v1(
        uptime: *mut c_ulong,
        operations: *mut c_ulong,
        errors: *mut c_ulong,
        bytes: *mut c_ulong,
    ) -> ConnectorResult;
}

// ---------------------------------------------------------------------------
// SAFE RUST WRAPPERS
// ---------------------------------------------------------------------------

/// Safe wrapper around connector_init().
pub fn init(config: &ConnectorConfig) -> Result<(), ConnectorError> {
    let result = unsafe { connector_init(config as *const ConnectorConfig) };
    if result.is_ok() {
        Ok(())
    } else {
        Err(ConnectorError::from_result(result, "connector_init"))
    }
}

/// Safe wrapper around connector_shutdown().
pub fn shutdown() -> Result<(), ConnectorError> {
    let result = unsafe { connector_shutdown() };
    if result.is_ok() {
        Ok(())
    } else {
        Err(ConnectorError::from_result(result, "connector_shutdown"))
    }
}

/// Safe wrapper around connector_send().
pub fn send(buffer: &ConnectorBuffer) -> Result<(), ConnectorError> {
    let result = unsafe { connector_send(buffer as *const ConnectorBuffer) };
    if result.is_ok() {
        Ok(())
    } else {
        Err(ConnectorError::from_result(result, "connector_send"))
    }
}

/// Safe wrapper around connector_receive().
pub fn receive(buffer: &mut ConnectorBuffer) -> Result<(), ConnectorError> {
    let result = unsafe { connector_receive(buffer as *mut ConnectorBuffer) };
    if result.is_ok() {
        Ok(())
    } else {
        Err(ConnectorError::from_result(result, "connector_receive"))
    }
}

/// Safe wrapper around connector_get_stats().
pub fn get_stats() -> Result<ConnectorStats, ConnectorError> {
    let mut stats = ConnectorStats {
        struct_size: std::mem::size_of::<ConnectorStats>() as c_uint,
        state: ConnectorState::Uninitialized,
        uptime_seconds: 0,
        total_operations: 0,
        successful_operations: 0,
        failed_operations: 0,
        timed_out_operations: 0,
        retried_operations: 0,
        bytes_sent: 0,
        bytes_received: 0,
        messages_sent: 0,
        messages_received: 0,
        active_connections: 0,
        peak_connections: 0,
        queue_depth: 0,
        peak_queue_depth: 0,
        average_latency_us: 0,
        peak_latency_us: 0,
        errors_by_type: [0; 32],
        warnings_count: 0,
        last_error_code: 0,
        last_error_message: [0i8; 256],
        reserved: [0; 16],
    };
    let result = unsafe { connector_get_stats(&mut stats as *mut ConnectorStats) };
    if result.is_ok() {
        Ok(stats)
    } else {
        Err(ConnectorError::from_result(result, "connector_get_stats"))
    }
}

/// Safe wrapper around connector_version().
pub fn version() -> String {
    unsafe {
        let ptr = connector_version();
        if ptr.is_null() {
            return "unknown".to_string();
        }
        let cstr = std::ffi::CStr::from_ptr(ptr);
        cstr.to_string_lossy().into_owned()
    }
}

/// Safe wrapper around connector_has_feature().
pub fn has_feature(feature: FeatureFlag) -> bool {
    unsafe { connector_has_feature(feature) != 0 }
}

// ---------------------------------------------------------------------------
// ERROR TYPE
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub struct ConnectorError {
    pub result: ConnectorResult,
    pub context: String,
    pub message: String,
}

impl ConnectorError {
    pub fn from_result(result: ConnectorResult, context: &str) -> Self {
        Self {
            result,
            context: context.to_string(),
            message: format!("{} failed: {}", context, result),
        }
    }
}

impl std::fmt::Display for ConnectorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "[{}] {}", self.context, self.result)
    }
}

impl std::error::Error for ConnectorError {}
